name: Bug report
description: Report a bug
labels: [bug]

body:
  - type: input
    id: bug
    attributes:
      label: Bug
    validations:
      required: true

  - type: input
    id: result
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: input
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
