name: Feature request
description: Suggest an improvement
labels: [enhancement]

body:
  - type: input
    id: summary
    attributes:
      label: Feature
    validations:
      required: true

  - type: input
    id: problem
    attributes:
      label: Problem
    validations:
      required: true

  - type: input
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: input
    id: alternatives
    attributes:
      label: Alternatives

  - type: input
    id: context
    attributes:
      label: Additional context
