name: Feature request
description: Suggest something new
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        Describe the feature and why it would be useful.

  - type: textarea
    id: request
    attributes:
      label: Details
    validations:
      required: true
